version: "3.8"

services:
  frontend:
    build:
      context: ./
      dockerfile: frontend/Dockerfile
    ports:
      - "8050:8050"
    networks:
      extra_net:
    depends_on:
      - backend
    volumes:
      - ./setup.py:/runsor-project/setup.py
      - ./requirements.txt:/runsor-project/requirements.txt
      - ./backend:/runsor-project/backend
      - ./config:/runsor-project/config
      - ./data:/runsor-project/data
      - ./runsor:/runsor-project/runsor
      - ./stores:/runsor-project/stores
      - ./frontend:/runsor-project/frontend
    entrypoint: streamlit run --server.port=8050 frontend/app.py

  backend:
    build:
      context: ./
      dockerfile: backend/Dockerfile
    ports:
      - "8000:8000"
    networks:
      extra_net:
    volumes:
      - ./setup.py:/runsor-project/setup.py
      - ./requirements.txt:/runsor-project/requirements.txt
      - ./backend:/runsor-project/backend
      - ./config:/runsor-project/config
      - ./data:/runsor-project/data
      - ./runsor:/runsor-project/runsor
      - ./stores:/runsor-project/stores
      - ./frontend:/runsor-project/frontend
    entrypoint: gunicorn --bind :8000 --workers 1 --threads 8 --timeout 0 -k uvicorn.workers.UvicornWorker backend.api:app
networks:
  extra_net:
    external: true